import { QuizQuestion } from './types'

export const TIME_PER_QUESTION_SECONDS = 20

export const courseQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'What does GEO stand for in the context of AI search optimization?',
    options: [
      { key: 'a', text: 'Google Engine Optimization' },
      { key: 'b', text: 'Generative Engine Optimization' },
      { key: 'c', text: 'General Engagement Optimization' },
      { key: 'd', text: 'Generative Experience Orchestration' },
    ],
    correctAnswer: 'b',
    explanation: 'GEO stands for Generative Engine Optimization — the practice of optimizing content so it appears in AI-generated responses from tools like ChatGPT, Claude, Perplexity, and Gemini.',
    category: 'AI Search Fundamentals',
  },
  {
    id: 'q2',
    question: 'How do AI search engines fundamentally differ from traditional search engines in how they present results?',
    options: [
      { key: 'a', text: 'They show more ads than organic results' },
      { key: 'b', text: 'They synthesize information into direct answers rather than a list of links' },
      { key: 'c', text: 'They only show video content' },
      { key: 'd', text: 'They rank results purely by domain authority' },
    ],
    correctAnswer: 'b',
    explanation: 'AI search engines synthesize information from multiple sources into cohesive, direct answers — rather than presenting a ranked list of links for users to click through.',
    category: 'AI Search Fundamentals',
  },
  {
    id: 'q3',
    question: 'What is a "query fan-out" in AI search?',
    options: [
      { key: 'a', text: 'When a user asks the same question across multiple search engines' },
      { key: 'b', text: 'When an AI model breaks a complex query into multiple sub-queries to gather comprehensive information' },
      { key: 'c', text: 'When search results are distributed across multiple pages' },
      { key: 'd', text: 'When a query generates too many irrelevant results' },
    ],
    correctAnswer: 'b',
    explanation: 'Query fan-out is when an AI model decomposes a complex user query into multiple sub-queries, searches for each independently, then synthesizes the results into a single comprehensive answer.',
    category: 'Technical Components',
  },
  {
    id: 'q4',
    question: 'What is a "citation" in the context of AI-generated search responses?',
    options: [
      { key: 'a', text: 'A footnote in academic papers' },
      { key: 'b', text: 'When an AI model references a specific source or brand as the basis for information in its response' },
      { key: 'c', text: 'A paid placement within AI results' },
      { key: 'd', text: 'The number of times a website has been indexed' },
    ],
    correctAnswer: 'b',
    explanation: 'In AI search, a citation is when the AI model attributes information to a specific source, brand, or URL — indicating that source contributed to the answer. Citations are the new equivalent of ranking on page one.',
    category: 'AI Search Fundamentals',
  },
  {
    id: 'q5',
    question: 'Which content characteristic is MOST important for AI search visibility?',
    options: [
      { key: 'a', text: 'High keyword density' },
      { key: 'b', text: 'Factual accuracy with clear, structured information that directly answers questions' },
      { key: 'c', text: 'Lengthy content with over 3,000 words' },
      { key: 'd', text: 'Heavy use of images and multimedia' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models prioritize factual accuracy and clear, structured information. They look for content that directly answers questions with verifiable facts, not keyword-stuffed or artificially lengthened content.',
    category: 'Best Practices',
  },
  {
    id: 'q6',
    question: 'How is buyer research behavior shifting with the rise of AI search?',
    options: [
      { key: 'a', text: 'Buyers are visiting more websites during research' },
      { key: 'b', text: 'Buyers are getting synthesized answers upfront, reducing the number of sites they visit before making decisions' },
      { key: 'c', text: 'Buyers prefer print catalogs over digital research' },
      { key: 'd', text: 'Buyers are relying exclusively on social media for purchase decisions' },
    ],
    correctAnswer: 'b',
    explanation: 'AI search is compressing the buyer journey. Instead of visiting 10+ websites, buyers get synthesized answers from AI, often making shortlist decisions based on which brands the AI recommends — before ever visiting a website.',
    category: 'Buyer Behavior',
  },
  {
    id: 'q7',
    question: 'What is the primary difference between traditional SEO and Generative Engine Optimization (GEO)?',
    options: [
      { key: 'a', text: 'SEO focuses on ranking in link-based results; GEO focuses on being cited in AI-generated answers' },
      { key: 'b', text: 'SEO is free and GEO requires paid placement' },
      { key: 'c', text: 'SEO works for B2C and GEO only works for B2B' },
      { key: 'd', text: 'There is no meaningful difference between the two' },
    ],
    correctAnswer: 'a',
    explanation: 'SEO optimizes for ranking positions in traditional search results (blue links). GEO optimizes for being cited and recommended within AI-generated answers — a fundamentally different surface and evaluation criteria.',
    category: 'AI Search vs SEO',
  },
  {
    id: 'q8',
    question: 'What is Google\'s AI Overviews (formerly Search Generative Experience)?',
    options: [
      { key: 'a', text: 'A paid advertising format within Google Search' },
      { key: 'b', text: 'AI-generated summary answers that appear at the top of Google search results before traditional links' },
      { key: 'c', text: 'A separate search engine built by Google' },
      { key: 'd', text: 'An analytics tool for measuring search performance' },
    ],
    correctAnswer: 'b',
    explanation: 'AI Overviews are AI-generated summaries that appear at the top of Google search results. They synthesize information from multiple sources and can significantly reduce clicks to individual websites.',
    category: 'AI Search Fundamentals',
  },
  {
    id: 'q9',
    question: 'What role does structured data (schema markup) play in AI search?',
    options: [
      { key: 'a', text: 'It has no effect on AI search' },
      { key: 'b', text: 'It helps AI models understand and extract factual information from your content more reliably' },
      { key: 'c', text: 'It only affects voice search results' },
      { key: 'd', text: 'It replaces the need for written content' },
    ],
    correctAnswer: 'b',
    explanation: 'Structured data helps AI models parse and understand the facts on your pages. Schema markup for organizations, products, FAQs, and reviews makes it easier for AI to extract and cite your information accurately.',
    category: 'Technical Components',
  },
  {
    id: 'q10',
    question: 'What is the "zero-click" problem in AI search?',
    options: [
      { key: 'a', text: 'Users can\'t click on AI-generated results' },
      { key: 'b', text: 'AI provides complete answers directly, so users never click through to the source website' },
      { key: 'c', text: 'Search engines block all outbound links' },
      { key: 'd', text: 'Websites fail to load when clicked from AI results' },
    ],
    correctAnswer: 'b',
    explanation: 'Zero-click occurs when AI search provides such a comprehensive answer that users get what they need without clicking through to any website. This is a major concern for marketers who rely on organic traffic.',
    category: 'Impact on Marketers',
  },
  {
    id: 'q11',
    question: 'What should marketers AVOID when trying to optimize for AI search?',
    options: [
      { key: 'a', text: 'Creating factual, well-structured content' },
      { key: 'b', text: 'Keyword stuffing, thin content, and manipulative SEO tactics that worked for traditional search' },
      { key: 'c', text: 'Adding schema markup to web pages' },
      { key: 'd', text: 'Publishing content regularly' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models are sophisticated enough to detect and penalize manipulative tactics. Keyword stuffing, thin doorway pages, and other black-hat SEO practices are ineffective or harmful for AI search visibility.',
    category: 'Things to Avoid',
  },
  {
    id: 'q12',
    question: 'How does PPC (Pay-Per-Click) advertising differ from AI search optimization?',
    options: [
      { key: 'a', text: 'PPC guarantees placement through paid bids; AI search citations cannot currently be purchased directly' },
      { key: 'b', text: 'PPC and AI search optimization are identical strategies' },
      { key: 'c', text: 'PPC only works on mobile devices' },
      { key: 'd', text: 'AI search optimization is more expensive than PPC' },
    ],
    correctAnswer: 'a',
    explanation: 'PPC lets you pay for guaranteed ad placement. Currently, AI search citations are earned through content quality and authority — you cannot directly buy a mention in ChatGPT\'s or Claude\'s answers.',
    category: 'AI Search vs PPC',
  },
  {
    id: 'q13',
    question: 'What is E-E-A-T and why does it matter for AI search?',
    options: [
      { key: 'a', text: 'A content management system for AI' },
      { key: 'b', text: 'Experience, Expertise, Authoritativeness, and Trustworthiness — signals that AI models use to evaluate source credibility' },
      { key: 'c', text: 'An AI model training technique' },
      { key: 'd', text: 'A social media engagement metric' },
    ],
    correctAnswer: 'b',
    explanation: 'E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) are quality signals that both Google and AI models use to evaluate whether a source is credible enough to cite in their responses.',
    category: 'Best Practices',
  },
  {
    id: 'q14',
    question: 'How do AI models typically decide which brands to recommend in response to a query?',
    options: [
      { key: 'a', text: 'Exclusively based on advertising spend' },
      { key: 'b', text: 'Based on consensus across multiple credible sources, brand authority, and the quality of available information' },
      { key: 'c', text: 'Randomly selected from indexed websites' },
      { key: 'd', text: 'Based solely on website traffic volume' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models form brand recommendations based on the weight of evidence across their training data and retrieval sources. Consistent mentions across authoritative, independent sources significantly increase citation likelihood.',
    category: 'Technical Components',
  },
  {
    id: 'q15',
    question: 'What content format tends to perform best for AI-generated citations?',
    options: [
      { key: 'a', text: 'Long-form blog posts with personal opinions' },
      { key: 'b', text: 'Comparison pages, data-driven guides, and FAQ-style content with clear factual statements' },
      { key: 'c', text: 'Press releases with corporate jargon' },
      { key: 'd', text: 'Paywalled premium content' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models favor content that provides clear, factual, comparable information. Comparison pages, data-backed guides, and FAQ content directly answers the types of queries users bring to AI search tools.',
    category: 'Content Strategy',
  },
  {
    id: 'q16',
    question: 'What is "AI traffic attribution" and why is it challenging?',
    options: [
      { key: 'a', text: 'Tracking which AI model generated the most revenue — it\'s challenging because AI models often don\'t send referral headers' },
      { key: 'b', text: 'Measuring how fast AI loads a page' },
      { key: 'c', text: 'Counting the number of AI bots crawling your site' },
      { key: 'd', text: 'Determining which AI tool your team uses most' },
    ],
    correctAnswer: 'a',
    explanation: 'AI traffic attribution means identifying which website visits came from AI-generated recommendations. It\'s difficult because AI tools often don\'t pass standard referral data, making it hard to measure AI\'s impact on your pipeline.',
    category: 'Measuring AI Search',
  },
  {
    id: 'q17',
    question: 'What is likely to happen with paid advertising inside AI search interfaces?',
    options: [
      { key: 'a', text: 'Paid ads will disappear entirely' },
      { key: 'b', text: 'AI platforms will likely introduce sponsored placements within AI-generated answers, similar to how Google monetized search' },
      { key: 'c', text: 'Only Fortune 500 companies will be able to advertise' },
      { key: 'd', text: 'All AI search results will become paid placements' },
    ],
    correctAnswer: 'b',
    explanation: 'AI search platforms will almost certainly introduce advertising. Perplexity has already tested sponsored answers. Expect native ad formats embedded within AI responses — making organic AI visibility even more critical to establish now.',
    category: 'Future of AI Search',
  },
  {
    id: 'q18',
    question: 'What is a "knowledge graph" and how does it relate to AI search?',
    options: [
      { key: 'a', text: 'A social network visualization tool' },
      { key: 'b', text: 'A structured database of entities and their relationships that AI models use to understand and connect information' },
      { key: 'c', text: 'A chart showing search volume trends' },
      { key: 'd', text: 'A Google Ads reporting feature' },
    ],
    correctAnswer: 'b',
    explanation: 'Knowledge graphs are structured databases mapping entities (companies, products, people) and their relationships. AI models leverage these to understand context, verify facts, and make informed recommendations.',
    category: 'Technical Components',
  },
  {
    id: 'q19',
    question: 'Which of the following is a common mistake marketers make when approaching AI search?',
    options: [
      { key: 'a', text: 'Creating genuinely helpful content' },
      { key: 'b', text: 'Treating AI search optimization exactly like traditional SEO and only focusing on keywords and backlinks' },
      { key: 'c', text: 'Monitoring multiple AI models for brand mentions' },
      { key: 'd', text: 'Adding structured data to their website' },
    ],
    correctAnswer: 'b',
    explanation: 'A common mistake is applying traditional SEO playbooks directly to AI search. While some fundamentals overlap, AI search requires focus on factual content, entity relationships, and multi-source authority rather than just keywords and links.',
    category: 'Things to Avoid',
  },
  {
    id: 'q20',
    question: 'How should marketers think about the relationship between traditional SEO and AI search optimization?',
    options: [
      { key: 'a', text: 'They should abandon SEO entirely and focus only on AI' },
      { key: 'b', text: 'They are complementary — good SEO foundations support AI visibility, but AI search requires additional strategies' },
      { key: 'c', text: 'SEO and AI search are completely unrelated' },
      { key: 'd', text: 'AI search optimization will replace SEO within a year' },
    ],
    correctAnswer: 'b',
    explanation: 'SEO and GEO are complementary. Strong SEO foundations (technical health, quality content, authority) support AI visibility. But AI search also requires additional focus on factual density, entity clarity, and multi-source presence.',
    category: 'AI Search vs SEO',
  },
  {
    id: 'q21',
    question: 'What is "brand mention monitoring" in AI search?',
    options: [
      { key: 'a', text: 'Tracking social media mentions of your brand' },
      { key: 'b', text: 'Systematically querying AI models with relevant prompts to check if and how they mention your brand in responses' },
      { key: 'c', text: 'Setting up Google Alerts for your brand name' },
      { key: 'd', text: 'Monitoring competitor advertising spend' },
    ],
    correctAnswer: 'b',
    explanation: 'Brand mention monitoring in AI search means regularly querying AI models (ChatGPT, Claude, Gemini, Perplexity) with prompts your buyers would use, and tracking whether your brand appears in the responses.',
    category: 'Measuring AI Search',
  },
  {
    id: 'q22',
    question: 'What type of website content is LEAST likely to get cited by AI models?',
    options: [
      { key: 'a', text: 'Detailed comparison pages with specific data points' },
      { key: 'b', text: 'Generic, undifferentiated marketing copy with vague claims and no specific facts' },
      { key: 'c', text: 'FAQ pages answering specific customer questions' },
      { key: 'd', text: 'Case studies with measurable outcomes' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models skip over generic marketing fluff. Content like "We\'re the leading solution for..." with no supporting evidence provides nothing for AI to cite. Specific facts, data points, and verifiable claims get cited.',
    category: 'Content Strategy',
  },
  {
    id: 'q23',
    question: 'How might AI search impact the traditional marketing funnel?',
    options: [
      { key: 'a', text: 'It will have no impact on the marketing funnel' },
      { key: 'b', text: 'AI compresses the top-of-funnel, with buyers arriving further into the decision process because AI pre-filtered options for them' },
      { key: 'c', text: 'It will only affect bottom-of-funnel conversions' },
      { key: 'd', text: 'It will make the funnel longer with more touchpoints' },
    ],
    correctAnswer: 'b',
    explanation: 'AI search compresses the awareness and consideration stages. Buyers who ask AI "what\'s the best CRM for small teams?" get a shortlist instantly, bypassing traditional top-of-funnel content. They arrive at your site closer to a purchase decision.',
    category: 'Impact on Marketers',
  },
  {
    id: 'q24',
    question: 'What is the significance of "multi-source consensus" for AI search visibility?',
    options: [
      { key: 'a', text: 'It means you need the most backlinks' },
      { key: 'b', text: 'AI models are more likely to cite brands that are consistently mentioned across multiple independent, authoritative sources' },
      { key: 'c', text: 'It refers to using multiple social media platforms' },
      { key: 'd', text: 'It means publishing the same content on multiple pages' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models build confidence through consensus. When multiple credible, independent sources (review sites, industry publications, comparison pages) consistently mention your brand, AI models are far more likely to include you in responses.',
    category: 'Best Practices',
  },
  {
    id: 'q25',
    question: 'What emerging trend should marketers prepare for regarding AI and digital advertising?',
    options: [
      { key: 'a', text: 'Return to print advertising' },
      { key: 'b', text: 'AI agents making purchase decisions autonomously on behalf of users, requiring machine-readable product information' },
      { key: 'c', text: 'Complete elimination of all digital advertising' },
      { key: 'd', text: 'Mandatory government regulation of all search results' },
    ],
    correctAnswer: 'b',
    explanation: 'AI agents that research, compare, and even purchase on behalf of users are emerging. This means brands need machine-readable, factually accurate product information that AI agents can evaluate and act on programmatically.',
    category: 'Future of AI Search',
  },
]
