import { QuizQuestion } from './types'

export const TIME_PER_QUESTION_SECONDS = 20

export const courseQuestions: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'A B2B SaaS company ranks #1 on Google for "best project management tool" but is never mentioned by ChatGPT or Perplexity for the same query. What is the MOST likely root cause?',
    options: [
      { key: 'a', text: 'Their website lacks structured data markup' },
      { key: 'b', text: 'They have strong SEO but weak multi-source presence across independent review sites, publications, and comparison platforms' },
      { key: 'c', text: 'AI models have a bias against highly ranked Google results' },
      { key: 'd', text: 'Their domain authority isn\'t high enough for AI models to index' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models build recommendations from consensus across multiple independent sources — not from Google rankings. A site can rank #1 through strong backlinks and on-page SEO but still lack the diverse third-party presence (reviews, analyst coverage, comparison mentions) that AI models rely on for recommendations.',
    category: 'AI Search vs SEO',
  },
  {
    id: 'q2',
    question: 'When an AI model performs a "query fan-out" on the question "What CRM should a 50-person SaaS company use?", which set of sub-queries is most realistic?',
    options: [
      { key: 'a', text: '"CRM definition," "CRM history," "CRM market size," "CRM vendors list"' },
      { key: 'b', text: '"Best CRM for small business," "CRM pricing comparison mid-market," "CRM with SaaS integrations," "CRM reviews for teams under 100"' },
      { key: 'c', text: '"CRM software," "50-person company," "SaaS company tools," "company size software"' },
      { key: 'd', text: '"CRM Wikipedia," "Salesforce homepage," "HubSpot pricing," "Zoho features"' },
    ],
    correctAnswer: 'b',
    explanation: 'Query fan-out decomposes a complex question into multiple intent-aligned sub-queries that match how the information is typically structured on the web. The model targets different facets of the decision (pricing, reviews, size-specific recommendations, integration needs) — not generic definitions or direct brand homepage lookups.',
    category: 'Technical Components',
  },
  {
    id: 'q3',
    question: 'Your competitor gets cited by Claude in 70% of relevant queries. You analyze their content and find it\'s mostly mediocre blog posts. What is the most likely explanation?',
    options: [
      { key: 'a', text: 'Claude has a partnership deal with your competitor' },
      { key: 'b', text: 'Their blog posts are more keyword-optimized than yours' },
      { key: 'c', text: 'They have extensive presence on third-party review sites, comparison platforms, and industry publications that independently validate their brand' },
      { key: 'd', text: 'They published their content before your company existed, so it\'s in Claude\'s training data' },
    ],
    correctAnswer: 'c',
    explanation: 'AI citation is driven by multi-source consensus, not the quality of your own website alone. A brand with mediocre owned content but strong G2 reviews, analyst mentions, and industry publication features will outperform a brand with excellent blog content but weak third-party presence.',
    category: 'Best Practices',
  },
  {
    id: 'q4',
    question: 'A marketing team creates an llms.txt file and adds comprehensive schema markup to every page. After 3 months, their AI visibility hasn\'t improved. What did they likely neglect?',
    options: [
      { key: 'a', text: 'The schema markup syntax was incorrect' },
      { key: 'b', text: 'They didn\'t submit the llms.txt to AI model providers' },
      { key: 'c', text: 'Technical optimizations alone don\'t build the multi-source authority signals that AI models use to decide which brands to recommend' },
      { key: 'd', text: 'AI models take 12+ months to re-index websites' },
    ],
    correctAnswer: 'c',
    explanation: 'Schema markup and llms.txt improve how AI parses your content, but they don\'t address the core question: does the AI model trust your brand enough to recommend it? That requires third-party validation, review presence, and consistent mentions across independent sources.',
    category: 'Things to Avoid',
  },
  {
    id: 'q5',
    question: 'Perplexity cites your competitor\'s pricing page when users ask about pricing in your category, but never cites yours. Both pages have similar information. What is the most actionable difference to investigate?',
    options: [
      { key: 'a', text: 'Whether your pricing page uses more visually appealing design' },
      { key: 'b', text: 'Whether your pricing is presented in clean, crawlable HTML with specific numbers vs. locked behind a "Contact Sales" wall or rendered as images' },
      { key: 'c', text: 'Whether your pricing page has more inbound links' },
      { key: 'd', text: 'Whether Perplexity\'s crawler visits your site more frequently' },
    ],
    correctAnswer: 'b',
    explanation: 'Perplexity uses real-time retrieval and needs machine-readable content. Pricing pages that gate information behind "Contact Sales" or render pricing in images/JavaScript that can\'t be crawled are invisible to AI retrieval. Clean HTML with specific pricing tiers wins.',
    category: 'Technical Components',
  },
  {
    id: 'q6',
    question: 'A VP of Marketing sees AI search traffic growing 40% quarter-over-quarter in their analytics, but their pipeline from AI hasn\'t grown proportionally. What is the most likely explanation?',
    options: [
      { key: 'a', text: 'AI traffic has lower intent than organic search traffic' },
      { key: 'b', text: 'Most AI-influenced buyers never click through to your site — they form opinions from the AI response and may convert through branded search, direct visits, or other channels' },
      { key: 'c', text: 'AI visitors are mostly bots, not real users' },
      { key: 'd', text: 'Their website isn\'t optimized for AI-referred visitors' },
    ],
    correctAnswer: 'b',
    explanation: 'The measurable AI referral traffic is just the tip of the iceberg. Most AI influence is invisible — a buyer asks Claude for recommendations, gets your brand name, then Googles you directly or mentions you to a colleague. The "dark funnel" from AI is much larger than trackable referral clicks.',
    category: 'Measuring AI Search',
  },
  {
    id: 'q7',
    question: 'Google rolls out ads in AI Overviews for your category. Your organic AI Overview citations drop by 60%. What should your response prioritize?',
    options: [
      { key: 'a', text: 'Immediately allocate budget to AI Overview ads to recover lost visibility' },
      { key: 'b', text: 'File complaints with Google about the algorithm change' },
      { key: 'c', text: 'Diversify AI visibility across non-Google AI platforms (ChatGPT, Claude, Perplexity) while testing AI Overview ads, since Google is just one surface' },
      { key: 'd', text: 'Double down on traditional SEO to compensate for lost AI Overview presence' },
    ],
    correctAnswer: 'c',
    explanation: 'Concentrating on a single AI surface is the same mistake brands made depending solely on Google organic. The right response is platform diversification — maintain presence across ChatGPT, Claude, Perplexity, and Gemini — while tactically testing the new ad format.',
    category: 'Future of AI Search',
  },
  {
    id: 'q8',
    question: 'You run the same query across ChatGPT, Claude, Perplexity, and Gemini. ChatGPT recommends your brand, but the other three don\'t mention you at all. What does this pattern suggest?',
    options: [
      { key: 'a', text: 'ChatGPT is the most accurate AI model for your category' },
      { key: 'b', text: 'Your brand information is likely present in ChatGPT\'s training data but you lack the real-time web presence that retrieval-based models rely on' },
      { key: 'c', text: 'The other three models have a bias against your brand' },
      { key: 'd', text: 'You need to optimize your content specifically for each AI model separately' },
    ],
    correctAnswer: 'b',
    explanation: 'Different models have different knowledge sources. ChatGPT draws heavily from training data (historical web content), while Perplexity uses real-time retrieval. If only training-data-heavy models cite you, it suggests your current web presence is weak even if historical content existed.',
    category: 'Technical Components',
  },
  {
    id: 'q9',
    question: 'A content marketer publishes a comprehensive 5,000-word guide optimized for AI visibility. It ranks well on Google but gets zero AI citations after 2 months. Which factor is MOST likely the issue?',
    options: [
      { key: 'a', text: 'The guide is too long for AI models to process' },
      { key: 'b', text: 'The guide contains original analysis but no other authoritative source references or links to the same conclusions, so AI models can\'t corroborate the claims' },
      { key: 'c', text: '5,000 words exceeds the token limit for AI retrieval' },
      { key: 'd', text: 'AI models only cite content from .edu and .gov domains' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models are cautious about citing claims they can\'t corroborate across sources. A single page — even a great one — that makes claims no other source validates is risky for an AI to cite. The content needs to be part of a broader ecosystem of supporting evidence.',
    category: 'Content Strategy',
  },
  {
    id: 'q10',
    question: 'Your brand is mentioned by Perplexity but the description is inaccurate — it confuses your product with a competitor\'s. What is the most effective fix?',
    options: [
      { key: 'a', text: 'Contact Perplexity to correct the error directly' },
      { key: 'b', text: 'Update your own website with clearer positioning and ensure third-party sources (review sites, comparison pages, your company About page) consistently and accurately describe your product\'s distinct capabilities' },
      { key: 'c', text: 'Add disclaimers to your website correcting the AI\'s claims' },
      { key: 'd', text: 'Create blog posts specifically addressing the inaccuracy' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models synthesize from multiple sources. The most effective fix is ensuring consistent, accurate information across your own site AND third-party platforms. If all sources clearly differentiate your product, retrieval-based models will self-correct on subsequent queries.',
    category: 'Best Practices',
  },
  {
    id: 'q11',
    question: 'Two competing brands have similar G2 ratings and feature sets. Brand A gets recommended by AI 3x more often. After analysis, the key difference is that Brand A has detailed "vs" comparison pages for each competitor. Why does this matter for AI specifically?',
    options: [
      { key: 'a', text: 'Comparison pages have higher keyword density for competitive terms' },
      { key: 'b', text: 'AI models frequently handle comparative queries ("X vs Y", "best alternative to Z") and comparison content directly provides the structured, factual data they need to synthesize competitive answers' },
      { key: 'c', text: 'Google penalizes brands without comparison pages, affecting AI visibility indirectly' },
      { key: 'd', text: 'Comparison pages generate more backlinks which AI models use as authority signals' },
    ],
    correctAnswer: 'b',
    explanation: 'Comparative queries are among the most common in AI search. When a user asks "X vs Y," the AI needs structured comparative data. Brands that create detailed comparison content give AI exactly what it needs to include them in these high-intent responses.',
    category: 'Content Strategy',
  },
  {
    id: 'q12',
    question: 'A marketing team tracks that 30% of their demo requests now mention "I asked ChatGPT" as their source. Standard analytics shows AI referral traffic accounts for only 2% of site visits. How should they reconcile this?',
    options: [
      { key: 'a', text: 'The survey data is unreliable — trust the analytics' },
      { key: 'b', text: 'Analytics undercount AI influence because most AI-influenced visitors arrive via branded search, direct visits, or word-of-mouth after seeing an AI recommendation — not through trackable AI referral links' },
      { key: 'c', text: 'ChatGPT is sending traffic that analytics tools can\'t detect' },
      { key: 'd', text: '28% of respondents are confusing ChatGPT with Google search' },
    ],
    correctAnswer: 'b',
    explanation: 'This 15x gap between self-reported AI influence and measured AI referral traffic is common. AI creates a large "dark funnel" — users get brand awareness from AI, then navigate to you through channels that don\'t carry AI attribution data.',
    category: 'Measuring AI Search',
  },
  {
    id: 'q13',
    question: 'E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) matters for AI search. Which E-E-A-T signal is HARDEST to replicate and most defensible for AI visibility?',
    options: [
      { key: 'a', text: 'Expertise — having well-researched content on your website' },
      { key: 'b', text: 'Authoritativeness — being consistently referenced as a category authority across independent third-party sources over time' },
      { key: 'c', text: 'Experience — including first-person accounts in blog posts' },
      { key: 'd', text: 'Trustworthiness — having an SSL certificate and privacy policy' },
    ],
    correctAnswer: 'b',
    explanation: 'Authoritativeness built through consistent third-party references is the hardest signal to fake or quickly replicate. You can improve your own site content overnight, but building genuine external authority across review sites, analyst reports, and publications takes sustained effort.',
    category: 'AI Search Fundamentals',
  },
  {
    id: 'q14',
    question: 'An AI agent is tasked by a procurement team to evaluate 5 CRM vendors and recommend the best fit. The agent will perform this evaluation programmatically. Which content asset will be MOST valuable to the agent?',
    options: [
      { key: 'a', text: 'A beautifully designed interactive demo' },
      { key: 'b', text: 'Customer video testimonials on your homepage' },
      { key: 'c', text: 'A machine-readable API endpoint or structured data page with specific feature capabilities, pricing tiers, integration lists, SLA terms, and security certifications' },
      { key: 'd', text: 'A detailed blog post about your company culture and mission' },
    ],
    correctAnswer: 'c',
    explanation: 'AI agents evaluate programmatically — they need structured, comparable data. Interactive demos, videos, and culture posts are human-facing. Machine-readable product data with specific, comparable attributes is what an AI agent can actually process and score.',
    category: 'Future of AI Search',
  },
  {
    id: 'q15',
    question: 'Your brand is in the cybersecurity space. ChatGPT consistently recommends a competitor, CyberGuard, for enterprise security queries. You analyze CyberGuard\'s web presence and find they have fewer backlinks, lower domain authority, and less organic traffic than you. But they have 2,400 G2 reviews vs. your 180. What does this reveal about AI recommendation signals?',
    options: [
      { key: 'a', text: 'G2 reviews are the single most important factor for AI recommendations' },
      { key: 'b', text: 'AI models weight user-generated validation signals (reviews, ratings) from trusted third-party platforms differently than traditional SEO signals like backlinks and domain authority' },
      { key: 'c', text: 'CyberGuard must be paying G2 for preferential treatment that flows into AI' },
      { key: 'd', text: 'ChatGPT indexes G2 directly and ignores other signals' },
    ],
    correctAnswer: 'b',
    explanation: 'Traditional SEO authority (backlinks, domain authority) and AI recommendation confidence are driven by different signals. AI models heavily weight consensus from trusted platforms like G2 because review volume from real users is a strong trust signal that\'s hard to manipulate.',
    category: 'AI Search vs SEO',
  },
  {
    id: 'q16',
    question: 'Your company launches a new product category that didn\'t exist 6 months ago. No AI model mentions you for related queries. What is the fastest path to AI visibility for a brand-new category?',
    options: [
      { key: 'a', text: 'Publish extensive SEO content and wait for AI models to re-train on it' },
      { key: 'b', text: 'Buy ads on Google to increase awareness, which will trickle into AI' },
      { key: 'c', text: 'Get covered by industry publications, launch on Product Hunt, secure analyst briefings, and build presence on retrieval-accessible platforms so real-time AI search tools pick you up before the next training cycle' },
      { key: 'd', text: 'Create a Wikipedia article about your new category' },
    ],
    correctAnswer: 'c',
    explanation: 'For a new category, you need to be discoverable by both retrieval-based AI (Perplexity, ChatGPT browsing) and baked into future training data. Third-party press, analyst coverage, and platforms that AI retrieval systems index (Product Hunt, TechCrunch, etc.) get you into AI responses fastest.',
    category: 'Best Practices',
  },
  {
    id: 'q17',
    question: 'A marketer notices that AI models cite their blog posts but never their product pages. They want product citations. What is the most likely structural problem with their product pages?',
    options: [
      { key: 'a', text: 'Product pages don\'t get enough organic traffic to be noticed by AI' },
      { key: 'b', text: 'Product pages typically use persuasive marketing copy with subjective claims rather than specific, factual, citable information that AI models can confidently attribute' },
      { key: 'c', text: 'AI models are programmed to avoid citing commercial pages' },
      { key: 'd', text: 'Product pages are usually not included in sitemaps' },
    ],
    correctAnswer: 'b',
    explanation: 'Most product pages say "Our industry-leading solution empowers teams to..." — this is persuasive but not citable. AI needs specific facts: "Handles 10M events/day, integrates with 200+ tools, prices start at $49/seat/month." Factual density drives product page citations.',
    category: 'Content Strategy',
  },
  {
    id: 'q18',
    question: 'You\'re allocating budget for Q3. Currently 90% goes to Google Ads, 10% to SEO content. Your AI visibility score is 15%. A colleague argues you should move 30% of Google Ads budget to AI optimization. What\'s the most pragmatic response?',
    options: [
      { key: 'a', text: 'Agree — 30% reallocation is appropriate given AI growth trends' },
      { key: 'b', text: 'Disagree — keep Google Ads budget intact since AI can\'t be measured' },
      { key: 'c', text: 'Start with 10-15% reallocation focused on high-ROI activities (review generation, comparison content, third-party presence) while building attribution to justify larger shifts based on evidence' },
      { key: 'd', text: 'Wait until AI platforms launch their own ad products before reallocating any budget' },
    ],
    correctAnswer: 'c',
    explanation: 'Cutting 30% of proven Google Ads revenue without AI attribution data is reckless. Waiting is equally risky. The pragmatic path is incremental reallocation toward high-confidence activities while building measurement capabilities to justify further shifts.',
    category: 'Impact on Marketers',
  },
  {
    id: 'q19',
    question: 'A buyer asks Perplexity: "What\'s the best marketing automation tool for a Series B SaaS startup with 50 employees?" Perplexity cites 6 sources in its answer. What primarily determined which sources it selected?',
    options: [
      { key: 'a', text: 'The 6 highest-ranking Google results for the query' },
      { key: 'b', text: 'The 6 most recently published articles on the topic' },
      { key: 'c', text: 'Sources that Perplexity\'s retrieval system scored as most relevant to the specific query context (B2B, Series B, 50 employees, marketing automation) based on content match and source authority' },
      { key: 'd', text: 'A random sample from a pre-approved list of trusted domains' },
    ],
    correctAnswer: 'c',
    explanation: 'Perplexity uses its own retrieval ranking that considers query-content relevance, source authority, and specificity match. It\'s not pulling Google\'s top results — it independently evaluates which sources best address the specific context of the query.',
    category: 'Technical Components',
  },
  {
    id: 'q20',
    question: 'Your team publishes identical content on your blog and as a guest post on a high-authority industry publication. Which is more likely to be cited by AI, and why?',
    options: [
      { key: 'a', text: 'Your blog — AI models prefer original source content' },
      { key: 'b', text: 'The industry publication — AI models give higher citation priority to independent, authoritative domains over brand-owned content, even when the content is identical' },
      { key: 'c', text: 'Both equally — AI doesn\'t distinguish between domains' },
      { key: 'd', text: 'Neither — AI penalizes duplicate content across domains' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models weight source authority heavily. The same factual claim from an independent industry publication carries more weight than from a brand\'s own blog, because third-party sources are perceived as less biased. This is why off-site content strategy is critical for AI visibility.',
    category: 'AI Search vs SEO',
  },
  {
    id: 'q21',
    question: 'You monitor your AI visibility weekly. For 3 consecutive weeks, your citation rate dropped from 45% to 20% across all models. What should you investigate FIRST?',
    options: [
      { key: 'a', text: 'Check if AI models were updated or retrained recently' },
      { key: 'b', text: 'Check if a competitor published a wave of new comparison content or review site activity that shifted the consensus signals AI models rely on' },
      { key: 'c', text: 'Check if your website had a technical SEO issue (downtime, crawl blocks, robots.txt changes) that prevented AI retrieval systems from accessing your content' },
      { key: 'd', text: 'Increase your content publishing frequency to regain visibility' },
    ],
    correctAnswer: 'c',
    explanation: 'A sudden, cross-platform drop points to a systematic issue with your content accessibility rather than competitive shifts (which would be gradual). Technical problems — crawl blocks, robots.txt changes, CDN issues, or accidental noindex tags — can instantly cut you off from retrieval-based AI systems.',
    category: 'Measuring AI Search',
  },
  {
    id: 'q22',
    question: 'The concept of "zero-click" search exists in both traditional Google and AI search, but the implications differ. How is AI zero-click fundamentally different from Google\'s featured snippet zero-click?',
    options: [
      { key: 'a', text: 'AI zero-click is temporary — users always eventually visit the source site' },
      { key: 'b', text: 'Google featured snippets still show your URL and brand; AI responses may synthesize your information into an answer without any visible attribution, making the source completely invisible' },
      { key: 'c', text: 'AI zero-click only affects informational queries, not commercial ones' },
      { key: 'd', text: 'There\'s no meaningful difference — both prevent clicks equally' },
    ],
    correctAnswer: 'b',
    explanation: 'Google\'s zero-click at least displays your URL and brand name in the featured snippet. AI can synthesize your information into a response with zero attribution — the user gets value from your content without ever knowing you exist. This makes brand-level mentions within AI responses critical.',
    category: 'Impact on Marketers',
  },
  {
    id: 'q23',
    question: 'A company has excellent AI visibility in English-language queries but zero presence in Spanish, German, and Japanese AI queries despite operating in those markets. Which approach addresses this most effectively?',
    options: [
      { key: 'a', text: 'Translate your English content to those languages using AI translation' },
      { key: 'b', text: 'Build native-language presence on local review platforms, publications, and directories in each market, since AI models for those languages draw from different source ecosystems than English' },
      { key: 'c', text: 'Add hreflang tags to your website for each language' },
      { key: 'd', text: 'Target multilingual keywords in your English content' },
    ],
    correctAnswer: 'b',
    explanation: 'AI models serving different languages draw from different source ecosystems. Spanish-language AI responses are shaped by Spanish-language review sites, publications, and web content — not translations of English pages. Building native-language third-party presence in each market is the real solution.',
    category: 'Best Practices',
  },
  {
    id: 'q24',
    question: 'In the traditional marketing funnel, top-of-funnel content (blog posts, guides) drives awareness. How has AI search changed the relationship between content type and funnel stage?',
    options: [
      { key: 'a', text: 'AI makes top-of-funnel content more important than ever' },
      { key: 'b', text: 'AI search compresses the funnel — a single AI response can take a buyer from unaware to shortlist in seconds, making mid-funnel comparison and bottom-funnel product content disproportionately valuable for AI optimization' },
      { key: 'c', text: 'AI search eliminates the need for bottom-of-funnel content since AI closes deals' },
      { key: 'd', text: 'The funnel stages are the same; only the channel has changed' },
    ],
    correctAnswer: 'b',
    explanation: 'AI collapses multiple funnel stages into a single interaction. A buyer who asks "What CRM should I use?" gets awareness, consideration, AND recommendations in one response. This makes comparison content and detailed product information more AI-valuable than traditional awareness content.',
    category: 'Buyer Behavior',
  },
  {
    id: 'q25',
    question: 'An early-stage startup with no brand recognition asks you how to build AI visibility from zero. They have limited budget. What should they prioritize FIRST?',
    options: [
      { key: 'a', text: 'Create comprehensive blog content targeting category keywords' },
      { key: 'b', text: 'Build a detailed, fact-dense website with clear category positioning, then immediately pursue review site profiles (G2, Capterra) and customer reviews — these create the minimum viable third-party presence AI models need' },
      { key: 'c', text: 'Invest in PR to get major publication features' },
      { key: 'd', text: 'Focus on social media presence to build brand awareness that feeds into AI' },
    ],
    correctAnswer: 'b',
    explanation: 'For a budget-constrained startup, the highest-ROI path is: (1) make your own site a clear, factual source of truth, then (2) build minimum viable third-party presence through free review platforms. Blog content and PR help but don\'t establish the multi-source validation foundation AI needs.',
    category: 'AI Search Fundamentals',
  },
]
