/**
 * Send PRD document via Resend API
 * Usage: npx tsx scripts/send-prd-email.ts
 */

import { config } from 'dotenv'
config({ path: '.env.local' })
import * as fs from 'fs'
import * as path from 'path'

const RESEND_API_KEY = process.env.RESEND_API_KEY

if (!RESEND_API_KEY) {
  console.error('❌ RESEND_API_KEY not found in environment')
  process.exit(1)
}

async function sendEmail() {
  // Read the PRD document (clean slate version)
  const prdPath = path.join(__dirname, '../docs/PRD_CLEAN_SLATE.md')
  const prdContent = fs.readFileSync(prdPath, 'utf-8')
  
  // Convert markdown to simple HTML (basic conversion)
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }
    h1 { color: #1a1a1a; border-bottom: 2px solid #0066cc; padding-bottom: 10px; }
    h2 { color: #333; margin-top: 30px; }
    h3 { color: #555; }
    code { background: #f4f4f4; padding: 2px 6px; border-radius: 3px; font-size: 14px; }
    pre { background: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; }
    table { border-collapse: collapse; width: 100%; margin: 15px 0; }
    th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    th { background: #f8f8f8; }
    blockquote { border-left: 4px solid #0066cc; margin: 0; padding-left: 15px; color: #666; }
    .moat { background: #e8f5e9; padding: 10px; border-radius: 5px; margin: 10px 0; }
    .remove { background: #ffebee; padding: 10px; border-radius: 5px; margin: 10px 0; }
    .keep { background: #e3f2fd; padding: 10px; border-radius: 5px; margin: 10px 0; }
  </style>
</head>
<body>
  <p><strong>From:</strong> Context Memo AI Architecture Review</p>
  <p><strong>Date:</strong> ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
  <p><strong>Subject:</strong> Context Memo V2 - Product Requirements Document</p>
  <hr/>
  
  <p>Hi Stephen,</p>
  
  <p>Attached below is the <strong>Clean Slate PRD</strong> for Context Memo. This is a fresh document describing what to build - no references to legacy features or what to remove.</p>
  
  <h3>Core Concept:</h3>
  <p><strong>Entities, not just competitors.</strong> When AI responds to a prompt, it cites competitors, resources (FDA.gov), aggregators (G2), partners, and publishers. We classify them all and provide different strategies for each.</p>
  
  <h3>The Workflow:</h3>
  <ol>
    <li><strong>Brand Intelligence</strong> - Extract products, markets, personas, tone</li>
    <li><strong>Prompt Generation</strong> - Persona-based reverse engineering ("what would they ask if they didn't know the brand?")</li>
    <li><strong>Baseline Scan</strong> - Run prompts → Entities discovered from AI responses</li>
    <li><strong>Daily Monitoring</strong> - Track changes, streaks, new entities</li>
    <li><strong>Content Generation</strong> - Create content for gaps, sync to HubSpot</li>
    <li><strong>Verification</strong> - Re-scan to prove content works</li>
    <li><strong>Attribution</strong> - Connect AI traffic to HubSpot revenue</li>
    <li><strong>Cascade</strong> - Analyze any entity to expand the visibility map</li>
  </ol>
  
  <h3>Key MOATs:</h3>
  <ul>
    <li><strong>Closed-Loop Verification</strong> (95/100) - Prove content works</li>
    <li><strong>Organic Entity Discovery</strong> (92/100) - AI responses are truth</li>
    <li><strong>Entity Classification</strong> (91/100) - Different strategies for competitors vs resources vs aggregators</li>
    <li><strong>Revenue Attribution</strong> (90/100) - AI traffic → Revenue</li>
    <li><strong>Cascade Analysis</strong> (88/100) - Expand the visibility map</li>
  </ul>
  
  <hr/>
  
  <h2>Full Document</h2>
  
  <pre style="white-space: pre-wrap; font-size: 12px; max-height: 2000px; overflow-y: auto;">${prdContent.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
  
  <hr/>
  <p style="color: #666; font-size: 12px;">This document was auto-generated by the AI Architecture Review. The full markdown file is available at <code>docs/PRD_V2_ARCHITECTURE.md</code> in your repository.</p>
</body>
</html>
`

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'Context Memo <onboarding@resend.dev>',
      to: ['stephen@krezzo.com'],
      subject: 'Context Memo - Clean Slate PRD (Developer Handoff)',
      html: htmlContent,
    }),
  })

  if (!response.ok) {
    const error = await response.text()
    console.error('❌ Failed to send email:', error)
    process.exit(1)
  }

  const result = await response.json()
  console.log('✅ Email sent successfully!')
  console.log('📧 Email ID:', result.id)
  console.log('📬 Sent to: stephen@krezzo.com')
}

sendEmail().catch(console.error)
